In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("a1_orders_messy.csv")

In [5]:
df.head()

,Order ID,Customer Name,City,Restaurant,Total (SAR),Order Date,Rating
0,101,Sara Al-Otaibi,Riyadh,Al Baik,"1,200",2026-03-01,5.0
1,102,omar khan,jeddah,Kudu,SAR 85,2026-03-02,4.0
2,103,Lina Said,Riyadh,Herfy,95,2026-03-03,NaN
3,104,Noura A.,RIYADH,Al Baik,NaN,2026-03-04,3.0
4,105,Faisal,Dammam,Maestro Pizza,250,2026-03-05,5.0

displays the first five rows of a DataFrame

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       22 non-null     int64
 1   Customer Name  22 non-null     object
 2   City           22 non-null     object
 3   Restaurant     22 non-null     object
 4   Total (SAR)    20 non-null     object
 5   Order Date     19 non-null     object
 6   Rating         20 non-null     float64
dtypes: float64(1), int64(1), object(5)
memory usage: 1.3+ KB

shows basic information about the data such as columns, data types, and missing values

In [7]:
df.describe(include="all")

,Order ID,Customer Name,City,Restaurant,Total (SAR),Order Date,Rating
count,22.000000,22,22,22,20,19,20.000000
unique,NaN,20,10,4,18,18,NaN
top,NaN,Sara Al-Otaibi,Dammam,Al Baik,"1,200",2026-03-01,NaN
freq,NaN,2,6,8,2,2,NaN
mean,110.454545,NaN,NaN,NaN,NaN,NaN,6.550000
std,6.277149,NaN,NaN,NaN,NaN,NaN,11.450006
min,101.000000,NaN,NaN,NaN,NaN,NaN,2.000000
25%,105.250000,NaN,NaN,NaN,NaN,NaN,3.000000
50%,110.500000,NaN,NaN,NaN,NaN,NaN,4.000000
75%,115.750000,NaN,NaN,NaN,NaN,NaN,5.000000
max,120.000000,NaN,NaN,NaN,NaN,NaN,55.000000

shows summary statistics for all columns in a data

In [8]:
df = pd.read_csv("a1_orders_messy.csv", dtype={"Order ID": "string"}, na_values=["", "NA", "-", "n/a"])
df.head()
df.info()
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       22 non-null     string
 1   Customer Name  22 non-null     object
 2   City           22 non-null     object
 3   Restaurant     22 non-null     object
 4   Total (SAR)    19 non-null     object
 5   Order Date     19 non-null     object
 6   Rating         20 non-null     float64
dtypes: float64(1), object(5), string(1)
memory usage: 1.3+ KB

,Order ID,Customer Name,City,Restaurant,Total (SAR),Order Date,Rating
count,22,22,22,22,19,19,20.000000
unique,20,20,10,4,17,18,NaN
top,00101,Sara Al-Otaibi,Dammam,Al Baik,"1,200",2026-03-01,NaN
freq,2,2,6,8,2,2,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,6.550000
std,NaN,NaN,NaN,NaN,NaN,NaN,11.450006
min,NaN,NaN,NaN,NaN,NaN,NaN,2.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,4.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,55.000000

Q1:
befor the last step we had:

Columns with missing values: Total (SAR), Order Date, and Rating

Wrong data types: Order ID should be a string, Total (SAR) should be numeric, and Order Date should be a datetime

In [9]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)


df = df.rename(columns={"total_sar": "total"})

print(df.columns)

Index(['order_id', 'customer_name', 'city', 'restaurant', 'total',
       'order_date', 'rating'],
      dtype='object')

Q2:
Yes, all column names are now clean and predictable

In [10]:
df["total"] = (
    df["total"]
    .astype(str)
    .str.replace(r"[^0-9.-]", "", regex=True)
)

df["total"] = pd.to_numeric(df["total"], errors="coerce")


df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")


print(df.dtypes)

order_id         string[python]
customer_name            object
city                     object
restaurant               object
total                   float64
order_date       datetime64[ns]
rating                  float64
dtype: object

In [11]:
df["total"].isna().sum()

np.int64(4)

Q3:
 4 values became NaN because they contained non-numeric or missing values, so they could not be converted to numbers

In [12]:
print(df["city"].value_counts())

df["customer_name"] = df["customer_name"].str.strip().str.title()
df["city"] = df["city"].str.strip().str.title()

df["city"] = df["city"].replace({
    "Jed": "Jeddah",
    "Ryd": "Riyadh"
})

print(df["city"].value_counts())

city
Dammam      6
Riyadh      4
jeddah      2
Jed         2
Jeddah      2
Ryd         2
 Riyadh     1
RIYADH      1
jeddah      1
RIYADH      1
Name: count, dtype: int64
city
Riyadh    9
Jeddah    7
Dammam    6
Name: count, dtype: int64

Q4:
The dataset started with 10 distinct cities and ended with 3 distinct cities

In [13]:
duplicates = df.duplicated().sum()

df = df.drop_duplicates()

df = df.dropna(subset=["total"])

df = df[df["total"] >= 0]

df = df[df["rating"] <= 5]

print("Duplicate rows removed:", duplicates)

Duplicate rows removed: 2

Q5:
I removed 2 duplicate rows and I dropped rows with missing total values because they can't be used in the analysis and also I removed negative total values because they are invalid and also removed ratings above 5 because the maximum rating is 5

In [16]:
df.groupby("city")["total"].agg(["count", "sum", "mean"])

        count     sum     mean
city
Dammam      3  1380.0  460.000
Jeddah      4  3305.5  826.375
Riyadh      5  2200.0  440.000

Q6:
Jeddah has the highest total sales and Jeddah also has the highest average order

In [17]:
df["restaurant"].value_counts()

restaurant
Al Baik          5
Maestro Pizza    3
Herfy            3
Kudu             1
Name: count, dtype: int64

In [18]:
df.to_csv("a1_orders_clean.csv", index=False)

Q7:
index=False stop pandas from saving the row index as an extra column, and saving to a new file keeps the original data unchanged so it can be used again if we need it

This dataset can answer which city has the highest total sales and in this assignment I collected the data by loading the CSV file and I wrangled the data by cleaning and fixing the dataset I have, then analyzed it using pandas libraray and Finally I communicated the results by answering the questions and saving the cleaned file